export const carpetsList = [
  { id: '001', title: 'Mesclado', desc: 'Tapete para Quarto',
      cor: 'Laranja, Amarelo e Cru', shape: 'Oval', price: '32,50', img: 'carpet-1' },
  { id: '002', title: 'Oreo', desc: 'Tapete para Banheiro',
      cor: 'Preto e Cinza', shape: 'Redondo', price: '32,00', img: 'carpet-2' },
  { id: '003', title: 'Red', desc: 'Tapete para Banheiro',
      cor: 'Vermelho e Branco', shape: 'Redondo', price: '33,50', img: 'carpet-3' },
  { id: '004', title: 'Cherry', desc: 'Tapete para Sala',
      cor: 'Vermelho', shape: 'Oval', price: '37,50', img: 'carpet-4' },
  { id: '005', title: 'Mickey', desc: 'Tapete para Quarto',
      cor: 'Preto e Azul', shape: 'Redondo', price: '40,00', img: 'carpet-5' },
  { id: '006', title: 'Eyes', desc: 'Tapete para Banheiro',
      cor: 'Preto e Branco', shape: 'Redondo', price: '35,50', img: 'carpet-6' },
  { id: '007', title: 'Pink Minnie', desc: 'Tapete para Quarto',
      cor: 'Preto e Rosa', shape: 'Redondo', price: '42,00', img: 'carpet-7' },
  { id: '008', title: 'Azulzinha', desc: 'Tapete para Banheiro',
      cor: 'Azul e Branco', shape: 'Redondo', price: '32,00', img: 'carpet-8' },
  { id: '009', title: 'Flowers', desc: 'Tapete para Banheiro',
      cor: 'Laranja e Cru', shape: 'Flor', price: '35,00', img: 'carpet-9' },
  { id: '010', title: 'Nuvem', desc: 'Tapete para Corredor',
      cor: 'Azul e Branco', shape: 'Oval', price: '37,50', img: 'carpet-10' },
  { id: '011', title: 'Flappy Bird', desc: 'Tapete para Banheiro',
      cor: 'Azul e Branco', shape: 'Redondo', price: '38,00', img: 'carpet-11' },
  { id: '012', title: 'Mickey & Minnie', desc: 'Tapete para Banheiro',
      cor: 'Preto, Vermelho e Amarelo', shape: 'Redondo', price: '40,00', img: 'carpet-12' },
  { id: '013', title: 'Sunflower', desc: 'Tapete para Banheiro',
      cor: 'Amarelo e Preto', shape: 'Estrela', price: '40,00', img: 'carpet-13' },
  { id: '014', title: 'Wind Vane', desc: 'Tapete para Sala',
      cor: 'Rosa', shape: 'Octógono', price: '42,50', img: 'carpet-14' },
  { id: '015', title: 'Speedway', desc: 'Tapete para Corredor',
      cor: 'Roxo e Cru', shape: 'Oval', price: '35,00', img: 'carpet-15' },
  { id: '016', title: 'Rosas', desc: 'Tapete para Banheiro',
      cor: 'Vermelho e Branco', shape: 'Flor', price: '35,50', img: 'carpet-16' },
  { id: '017', title: 'Quadro', desc: 'Tapete para Banheiro',
      cor: 'Preto e Branco', shape: 'Diversos', price: '32,50', img: 'carpet-17' },
  { id: '018', title: 'Hexagon', desc: 'Tapete para Sala',
      cor: 'Tons de Vinho', shape: 'Hexágonos', price: '50,00', img: 'carpet-18' },
  { id: '019', title: 'Minnie', desc: 'Tapete para Banheiro',
      cor: 'Vermelho e Preto', shape: 'Redondo', price: '42,00', img: 'carpet-19' },
  { id: '020', title: 'Corujinha', desc: 'Jogo de Banheiro',
      cor: 'Verde Claro/Escuro', shape: 'Redondo', price: '38,00', img: 'carpet-20' },
]